stages:
  - build
  - report

py35:
  image: python:3.5
  stage: build
  script:
    - pip install tox
    - tox -e py35-juniper,py35-latest,flake8
  artifacts:
    paths:
      - .coverage*
    expire_in: 5 minutes

py38:
  image: python:3.8
  stage: build
  script:
    - pip install tox
    - tox -e py38-juniper,py38-latest,flake8
  artifacts:
    paths:
      - .coverage*
    expire_in: 5 minutes

coverage:
  image: python:3
  stage: report
  script:
    - pip install coverage
    - python -m coverage combine
    - python -m coverage html
    - python -m coverage report
  coverage: '/TOTAL.*\s+(\d+\.\d+%)$/'
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 week
