# Generated by Django 3.2.11 on 2022-01-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_receiver_woocommerce', '0003_add_webhook_fk'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='woocommerceorderitem',
            name='unique_order_sku_email',
        ),
        migrations.AddConstraint(
            model_name='woocommerceorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'sku', 'email'), name='unique_woocommerce_order_sku_email'),
        ),
    ]
