# Generated by Django 2.2.14 on 2020-07-24 08:32

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('edx_shopify', '0002_fsm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Processed'), (-1, 'Error')], default=0, protected=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Processed'), (-1, 'Error')], default=0, protected=True),
        ),
    ]
