# Generated by Django 2.2.18 on 2021-02-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edx_woocommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='WooCommerceOrder',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='WooCommerceOrderItem',
        ),
    ]
